name: the-users
favicon: null
layout_spectrum: 0.724042265675962
typography_spectrum: 0.3474800034891814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1399895679205656
  lightness: 0.009478264022618532
  saturation: 0.8855425210203975
  rhythmicContrast: 0.08261216781102121
purpose: []
