name: the-users
favicon: null
layout_spectrum: 0.64539
typography_spectrum: 0.02709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75336334-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c0d5'
    - '#969581'
    - '#91c523'
    - '#458300'
    - '#b8e473'
  brandStrength: 0.875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
