name: the-users
favicon: null
layout_spectrum: 0.74174
typography_spectrum: 0.3474800034891814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0067c3'
    - '#260004'
    - '#00c380'
    - '#de873c'
  brandStrength: 1
  lightness: 0.009478264022618532
  saturation: 1
  rhythmicContrast: 0
purpose: []
