name: the-users
favicon: null
layout_spectrum: 0.64539
typography_spectrum: 0.02709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75336334-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#3b3736'
    - '#a7b8bf'
    - '#897b78'
  brandStrength: 0.875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
