name: the-users
favicon: null
layout_spectrum: 0.64539
typography_spectrum: 0.02709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75336334-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdd'
    - '#1e1f24'
    - '#8d8a85'
    - '#2ee125'
    - '#39a02b'
  brandStrength: 0.875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
